# Objectives

+ Check the CF performance by training on one, five and ten fields 

 
# Preparation

## Packages and functions
```{r}
#--- packages ---#
library(tidyverse)
library(data.table)
library(mgcv)
library(spatialsample)
library(parallel)
library(sf)
library(grf)
library(ranger)
library(xgboost)
library(mgcv)
# library(here)
library(reticulate)
library(readr)
library(dplyr)
library(tidyr)


#--- R functions ---#
# here("codes/R") %>%
#   fs::dir_ls(., full.names = TRUE) %>%
#   lapply(source)


#--- python functions ---#
use_condaenv("cf_conda311", required = TRUE)
py_config()
py_run_string("from econml.dml import CausalForestDML; print('CausalForestDML imported OK')")
source_python("/Users/mmousavi2/Dropbox/Causal_climate/My_own_Shared/Causal-ML-continuous-treatment/codes/Python/run_CF_c.py")
```



```{r}
# project‐root path:
proj_root <- "/Users/mmousavi2/Dropbox/Causal_climate/Data_and_results_CF_Continuous"

# “.here” file
here_file <- file.path(proj_root, ".here")
if (!file.exists(here_file)) {
  message("Creating .here in ", proj_root)
  file.create(here_file)
}


```

## Data

```{r}
# turn off multi-threading
Sys.setenv(OMP_NUM_THREADS = 1, MKL_NUM_THREADS = 1)

# load data only once, then drop
library(here)
raw_sim_data <- readRDS(here("data", "raw_sim_data.rds"))
rm(list = setdiff(ls(), c("raw_sim_data", "np", "run_CF_c_py", "gm_wrapper_functions_you_need")))
gc()
```

```{r}
source("/Users/mmousavi2/Dropbox/Causal_climate/My_own_Shared/Causal-ML-continuous-treatment/codes/R/Utility.R")
```

# Train CF (Train on five fields. We can simply change 5 to other numbers)

```{r}


# how many fields to train on?
n_fields <- 5

# ─── PATHS via here() ──────────────────────────────────────────────────────────

# the right split file under <project_root>/data/train_test_split
splits_file <- here(
  "data", "train_test_split",
  sprintf("train_test_splits_%dfields.csv", n_fields)
)
output_dir <- here(
  "results",
  sprintf("CF_outcome_%d_fields", n_fields)
)
if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)

# ─── LOAD SPLITS ────────────────────────────────────────────────────────────────

train_test_splits <- read_csv(splits_file)

# ─── MODEL LOOP ────────────────────────────────────────────────────────────────

x_vars    <- c("Nk", "plateau", "b0")
T_formula <- yield ~ s(N, k = 4)

# cf_results <- lapply(train_test_splits$test_id, function(test_sim_id)
cf_results <- lapply(train_test_splits$test_id, function(test_sim_id) {
  result_file <- file.path(output_dir, paste0("sim_", test_sim_id, ".rds"))
  if (file.exists(result_file)) {
    message(sprintf("Skipping sim %d (already saved)", test_sim_id))
    return(NULL)
  }

  tryCatch({
  
    split_row     <- train_test_splits[train_test_splits$test_id == test_sim_id, ]
    train_sim_ids <- as.integer(unlist(split_row[paste0("train_", 1:n_fields)]))

    sim_id_ls     <- c(train_sim_ids, test_sim_id)

    # assemble train & test data
    data <- raw_sim_data$reg_data[[1]] %>%
      .[sim %in% sim_id_ls, ] %>%
      .[, .(sim, data)] %>%
      unnest(cols = c(data)) %>%
      data.table()

    train_data <- data[sim != test_sim_id, ]
    test_data  <- raw_sim_data$reg_data[[1]] %>%
      .[sim == test_sim_id, ] %>%
      .[, .(sim, data)] %>%
      unnest(cols = c(data)) %>%
      data.table()

    # fit causal forest
    T_info     <- prepare_T_mat(T_formula, train_data)
    Y          <- train_data[, yield]
    X          <- train_data[, ..x_vars] %>% as.matrix()
    W          <- X
    te_hat_cf  <- run_CF_c_py(Y, T_info$T_sp, X, W, n_estimators = 2000)
    te_info    <- get_te(te_hat_cf, test_data, x_vars)

    # response & EONR
    T_seq      <- train_data[, seq(min(N), max(N), length.out = 200)]
    response_dt <- find_response_semi(T_seq, T_info, te_info)

    pCorn <- 6.25 / 25.4
    pN    <- 1 / 0.453592

    ss_eonr <- response_dt[
      , profit := est * pCorn - pN * T
    ][
      , .SD[which.max(profit)], by = aunit_id
    ][
      , .(aunit_id, opt_N_hat = T)
    ]

    # true EONR
   true_eonr <- raw_sim_data$reg_data[[1]] %>%

  .[sim == test_sim_id, ] %>%

  .[, .(sim, data)] %>%
  unnest(cols = c(data)) %>%
  data.table() %>%
  .[, .(aunit_id, b0, b1, b2, Nk)] %>%
  .[, opt_N := (pN / pCorn - b1) / (2 * b2)] %>%
  .[, opt_N := pmin(Nk, pmax(0, opt_N))] %>%
  .[, .(aunit_id, opt_N)]


    combined <- ss_eonr[true_eonr, on = "aunit_id"]
    combined[, sim := test_sim_id]

    saveRDS(combined, result_file)
    combined

  }, error = function(e) {
    message(sprintf("Error with sim %d: %s", test_sim_id, e$message))
    data.table(
      sim        = test_sim_id,
      aunit_id   = integer(),
      opt_N_hat  = numeric(),
      opt_N      = numeric()
    )
  })
})

```


